language: python
python:
- 3.4
env:
  matrix:
  - TOXENV=flake8
  - TOXENV=pylint
install:
- pip install tox bumpversion
script: tox -v
notifications:
  hipchat:
    rooms:
      secure: kEZDtvcCIKU6XSSLjKOFE7vNAtsIe7Zdl2cIRasGXnJia+mRI3C5AjnO5Nl82us752F4ozdR/H0aLQuhs3XX+sfYmdeXT7laAV99g0QTYngfVU7wgnBbIwaOs3y+dluoRjEWOQ+8ZqKQ0fNrabfYCr/vVEUg15NbGb5tMg7cFrE=
